/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-12-09 19:11:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import model.ChiTietSanPham;
import model.DanhMuc;
import model.SanPham;
import java.util.List;
import Reponsitory.LaydulieuReponsitory;

public final class productquantri_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.ChiTietSanPham");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.LaydulieuReponsitory");
    _jspx_imports_classes.add("model.SanPham");
    _jspx_imports_classes.add("model.DanhMuc");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>Admin/Product</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"assetsquantri/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"assetsquantri/img/apple-touch-icon.png\"\r\n");
      out.write("	rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"assetsquantri/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/bootstrap-icons/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/boxicons/css/boxicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/quill/quill.bubble.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/remixicon/remixicon.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/simple-datatables/style.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Main CSS File -->\r\n");
      out.write("<link href=\"assetsquantri/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Updated: Apr 20 2024 with Bootstrap v5.3.3\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* Che lớp mờ */\r\n");
      out.write("#smoke {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal chính */\r\n");
      out.write("#editF {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	transform: translate(-50%, -50%);\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Ẩn các phần tử */\r\n");
      out.write(".hide {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút đóng */\r\n");
      out.write(".close-btn {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 10px;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		");

	String projectName = request.getContextPath(); // Lấy tên dự án
	HttpSession s = request.getSession(false);
	List<User> listt = (session != null) ? (List<User>) session.getAttribute("Ghinhotaikhoan") : null;
	
      out.write("\r\n");
      out.write("	<!-- ======= Header ======= -->\r\n");
      out.write("	<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("			<div class=\"logo d-flex align-items-center\">\r\n");
      out.write("				<img src=\"assetsquantri/img/logo.png\" alt=\"\"> <span\r\n");
      out.write("					class=\"d-none d-lg-block\">T3admin</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<i class=\"bi bi-list toggle-sidebar-btn\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<nav class=\"header-nav ms-auto\">\r\n");
      out.write("			<ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("					\r\n");
      out.write("			<a class=\"nav-link nav-profile d-flex align-items-center pe-0\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\"> <i\r\n");
      out.write("						class=\"bi bi-person-circle\"></i> <span\r\n");
      out.write("						");
if(listt != null){
						for(User u : listt) {
      out.write("\r\n");
      out.write("						class=\"d-none d-md-block dropdown-toggle ps-2\">");
      out.print(u.getHoTen());
      out.write("\r\n");
      out.write("							</span>\r\n");
      out.write("				</a> <!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">\r\n");
      out.write("						<li class=\"dropdown-header\">\r\n");
      out.write("							<h6>");
      out.print(u.getTenTaiKhoan());
      out.write("</h6>\r\n");
      out.write("							");
if(u.getMaQuyen() == 1) {
      out.write("\r\n");
      out.write("							<span>Quản trị viên</span>\r\n");
      out.write("							");
} else{
      out.write("\r\n");
      out.write("							<span>Khách hàng</span>\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("						\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("							<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"Thongtincanhan.jsp\"> <i class=\"bi bi-person\"></i> <span>Thông tin cá nhân\r\n");
      out.write("									</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"Dangxuat\"> <i class=\"bi bi-box-arrow-right\"></i> <span>Đăng\r\n");
      out.write("									xuất</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul> <!-- End Profile Dropdown Items -->\r\n");
      out.write("				</li>\r\n");
      out.write("				");
} }
      out.write("\r\n");
      out.write("				<!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Sidebar ======= -->\r\n");
      out.write("\r\n");
      out.write("	<aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-heading\">Quản lý bán hàng</li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/category.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-layout-text-window-reverse\"></i> <span>Danh mục</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"");
      out.print(projectName);
      out.write("/Donhangquantri.jsp\">\r\n");
      out.write("					<i class=\"bi bi-cart\"></i> <span>Đơn hàng</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link \"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/productquantri.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-grid\"></i> <span>Sản phẩm</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-heading\">Quản lý tài khoản</li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/account.jsp\"> <i class=\"bi bi-person\"></i>\r\n");
      out.write("					<span>Tài khoản</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<!-- End Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/group.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-question-circle\"></i> <span>Phân quyền</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<!-- End F.A.Q Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</aside>\r\n");
      out.write("	<!-- End Sidebar-->\r\n");
      out.write("	<!-- End Sidebar-->\r\n");
      out.write("\r\n");
      out.write("	<main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"pagetitle\">\r\n");
      out.write("			<h1>Sản phẩm</h1>\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ol class=\"breadcrumb\">\r\n");
      out.write("					<li class=\"breadcrumb-item\"><a href=\"index.html\">Quản lý\r\n");
      out.write("							bán hàng</a></li>\r\n");
      out.write("					<li class=\"breadcrumb-item active\">Sản phẩm</li>\r\n");
      out.write("				</ol>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("		<section class=\"section\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h3 class=\"card-title\">\r\n");
      out.write("								<b>Quản lý sản phẩm</b>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<div\r\n");
      out.write("								style=\"display: flex; justify-content: flex-start; padding-left: 20px;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"display: flex; flex-direction: column; align-items: center; justify-content: center;\">\r\n");
      out.write("									<button type=\"button\" id=\"addb\" class=\"btn btn-success\">\r\n");
      out.write("										<i class=\"bi bi-plus-lg\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("									<p>Thêm sản phẩm</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body row hide\" id=\"addf\">\r\n");
      out.write("									<h5 class=\"card-title\">Thêm sản phẩm</h5>\r\n");
      out.write("\r\n");
      out.write("									<!-- Vertical Form -->\r\n");
      out.write("									<form action=\"Themsanphamproductquantri\" method=\"post\"\r\n");
      out.write("										enctype=\"multipart/form-data\">\r\n");
      out.write("										<div class=\"col-12\">\r\n");
      out.write("											<label for=\"inputName\" class=\"form-label\">Tên sản\r\n");
      out.write("												phẩm</label> <input type=\"text\" class=\"form-control\" id=\"inputName\"\r\n");
      out.write("												placeholder=\"Tên sản phẩm\" name=\"addTensanpham\"> <label\r\n");
      out.write("												for=\"categorySelect\" class=\"form-label\">Chọn danh\r\n");
      out.write("												mục của sản phẩm</label> <select class=\"form-select\"\r\n");
      out.write("												id=\"categorySelect\" name=\"addDanhmucsanpham\">\r\n");
      out.write("												<option selected>Chọn danh mục...</option>\r\n");
      out.write("												<option value=\"1\">Quần áo Nữ</option>\r\n");
      out.write("												<option value=\"2\">Quần áo Nam</option>\r\n");
      out.write("												<option value=\"3\">Phụ kiện</option>\r\n");
      out.write("												<option value=\"4\">Giày dép</option>\r\n");
      out.write("												<option value=\"5\">Túi xách</option>\r\n");
      out.write("											</select> <label for=\"inputPrice\" class=\"form-label\">Đơn giá</label> <input\r\n");
      out.write("												type=\"number\" class=\"form-control\" id=\"inputPrice\"\r\n");
      out.write("												placeholder=\"Đơn vị: $\" name=\"idGiasanpham\">\r\n");
      out.write("											<!-- <form id=\"uploadForm\" action=\"/upload\" method=\"post\"\r\n");
      out.write("												enctype=\"multipart/form-data\">\r\n");
      out.write("												<label for=\"inputImg\">Ảnh:</label><br> <input\r\n");
      out.write("													type=\"file\" id=\"inputImg\" name=\"image\" accept=\"image/*\"\r\n");
      out.write("													required>f\r\n");
      out.write("											</form> -->\r\n");
      out.write("											<label for=\"inputImg\">Ảnh:</label><br> <input\r\n");
      out.write("												type=\"file\" id=\"inputImg\" name=\"image\" accept=\"image/*\"\r\n");
      out.write("												required> <br> <label for=\"inputDetail\"\r\n");
      out.write("												class=\"form-label\">Mô tả</label> <input class=\"form-control\"\r\n");
      out.write("												id=\"inputDetail\" placeholder=\"Mô tả sản phẩm\" name=\"addMota\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div class=\"text-center\">\r\n");
      out.write("											<button type=\"submit\" class=\"btn btn-primary\">Thêm</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("									<!-- Vertical Form -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Table with stripped rows -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<table class=\"table datatable\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>Mã SP</th>\r\n");
      out.write("								<th>Tên SP</th>\r\n");
      out.write("								<th>Hình ảnh</th>\r\n");
      out.write("								<th>Số lượng</th>\r\n");
      out.write("								<th>Phân loại</th>\r\n");
      out.write("								<th>Giá</th>\r\n");
      out.write("								<th>Hành động</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

							int soluong;
							LaydulieuReponsitory ldl = new LaydulieuReponsitory();
							List<SanPham> sanpham = ldl.Laythongtinsanpham();
							List<DanhMuc> danhmuc = ldl.Laythongtidanhmuc();
							List<ChiTietSanPham> chitiet = ldl.Laythongtinchitietsanpham();
							int idxd = 0;
							for (SanPham sp : sanpham) {
								soluong = 0; // Khởi tạo lại mỗi lần lặp qua sản phẩm mới
							
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>");
      out.print(sp.getMaSanpham());
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print(sp.getTenSanPham());
      out.write("</td>\r\n");
      out.write("								<td><img src=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\"\r\n");
      out.write("									alt=\"");
      out.print(sp.getTenSanPham());
      out.write("\"\r\n");
      out.write("									style=\"width: 100px; height: auto;\" loading=\"lazy\"></td>\r\n");
      out.write("								");

								// Tính tổng số lượng cho sản phẩm này
								for (ChiTietSanPham c : chitiet) {
									if (sp.getMaSanpham() == c.getMaSanPham()) {
										soluong += c.getSoLuong();
									}
								}
								sp.setSoLuong(soluong); // Sử dụng setter để gán giá trị cho soLuong
								
      out.write("\r\n");
      out.write("								<td>");
      out.print(sp.getSoLuong());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("								");

								for (DanhMuc dm : danhmuc) {
									if (dm.getMaDanhmuc() == sp.getMaDanhMuc()) {
								
      out.write("\r\n");
      out.write("								<td>");
      out.print(dm.getTenDanhMuc());
      out.write("</td>\r\n");
      out.write("								");

								}
								}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<td>");
      out.print(sp.getGia());
      out.write("</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<div class=\"d-flex justify-content-center mt-2\">\r\n");
      out.write("										<!-- Sửa Button -->\r\n");
      out.write("										<button type=\"button\" class=\"btn btn-outline-warning\"\r\n");
      out.write("											data-id=\"");
      out.print(sp.getMaSanpham());
      out.write("\" onclick=\"editForm(this)\">Sửa</button>\r\n");
      out.write("\r\n");
      out.write("										<!-- Xoá Button -->\r\n");
      out.write("										<form action=\"Xoasanphamproductqt\" method=\"post\" class=\"ml-3\">\r\n");
      out.write("											<input type=\"hidden\" value=\"");
      out.print(sp.getMaSanpham());
      out.write("\" name=\"id\">\r\n");
      out.write("											<button class=\"btn btn-outline-danger\" type=\"submit\">Xoá</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div> <!-- Chi tiết Button on a new line -->\r\n");
      out.write("									<div class=\"mt-1\">\r\n");
      out.write("										<form action=\"LayidSanPhamquantri\" method=\"post\">\r\n");
      out.write("											<input type=\"hidden\" value=\"");
      out.print(sp.getMaSanpham());
      out.write("\"\r\n");
      out.write("												name=\"idd\">\r\n");
      out.write("											<button type=\"submit\" class=\"btn btn-outline-info\"\r\n");
      out.write("												id=\"detailB\">Chi tiết</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("					<!-- End Table with stripped rows -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- 	<div class=\"card editForm hide\" id=\"editF\"\r\n");
      out.write("			style=\"top: 10%; left: 10%;\">\r\n");
      out.write("			<div class=\"card-body row \">\r\n");
      out.write("				<h5 class=\"card-title\">Sửa sản phẩm</h5>\r\n");
      out.write("\r\n");
      out.write("				Vertical Form\r\n");
      out.write("				<form>\r\n");
      out.write("					<label for=\"editName\" class=\"form-label\">Tên sản phẩm</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"editName\"\r\n");
      out.write("						placeholder=\"Tên sản phẩm\"> <label for=\"categorySelect\"\r\n");
      out.write("						class=\"form-label\">Chọn danh mục của sản phẩm</label> <select\r\n");
      out.write("						class=\"form-select\" id=\"editCategory\">\r\n");
      out.write("						<option selected>Chọn danh mục...</option>\r\n");
      out.write("						<option value=\"1\">Quần áo nam</option>\r\n");
      out.write("						<option value=\"2\">Quần áo nữ</option>\r\n");
      out.write("						<option value=\"3\">Phụ kiện</option>\r\n");
      out.write("						<option value=\"4\">Giày dép</option>\r\n");
      out.write("						<option value=\"5\">Túi xách</option>\r\n");
      out.write("					</select> <label for=\"editPrice\" class=\"form-label\">Đơn giá</label> <input\r\n");
      out.write("						type=\"number\" class=\"form-control\" id=\"editPrice\"\r\n");
      out.write("						placeholder=\"Đơn vị: $\">\r\n");
      out.write("					<form id=\"editUploadForm\" action=\"/upload\" method=\"post\"\r\n");
      out.write("						enctype=\"multipart/form-data\">\r\n");
      out.write("						<label for=\"editImg\">Ảnh:</label><br> <input type=\"file\"\r\n");
      out.write("							id=\"editImg\" name=\"image\" accept=\"image/*\" required>\r\n");
      out.write("					</form>\r\n");
      out.write("					<label for=\"editDetail\" class=\"form-label\">Mô tả</label> <input\r\n");
      out.write("						type=\"number\" class=\"form-control\" id=\"editDetail\"\r\n");
      out.write("						placeholder=\"Mô tả sản phẩm\">\r\n");
      out.write("\r\n");
      out.write("					<button type=\"submit\" id=\"cuppha\" class=\"btn btn-primary\">Sửa</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div> -->\r\n");
      out.write("		<div id=\"smoke\" class=\"hide\" onclick=\"closeModal(event)\"></div>\r\n");
      out.write("		<div id=\"editF\" class=\"hide\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<span class=\"close-btn\" onclick=\"closeModal()\">×</span>\r\n");
      out.write("				<form onsubmit=\"handleSave(event)\" class=\"card-body row\"\r\n");
      out.write("					id=\"editProductForm\" action=\"Suasanphamproductquantri\"\r\n");
      out.write("					method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<input type=\"hidden\" id=\"product-id\" name=\"product-id\" readonly>\r\n");
      out.write("\r\n");
      out.write("					<h5 class=\"card-title\">Sửa sản phẩm</h5>\r\n");
      out.write("\r\n");
      out.write("					<!-- Tên sản phẩm -->\r\n");
      out.write("					<label for=\"editName\" class=\"form-label\">Tên sản phẩm</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"editName\" name=\"name\"\r\n");
      out.write("						placeholder=\"Tên sản phẩm\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Chọn danh mục sản phẩm -->\r\n");
      out.write("					<label for=\"categorySelect\" class=\"form-label\">Chọn danh\r\n");
      out.write("						mục của sản phẩm</label> <select class=\"form-select\" id=\"editCategory\"\r\n");
      out.write("						name=\"category\">\r\n");
      out.write("						<option selected>Chọn danh mục...</option>\r\n");
      out.write("						<option value=\"1\">Nữ</option>\r\n");
      out.write("						<option value=\"2\">Nam</option>\r\n");
      out.write("						<option value=\"3\">Túi</option>\r\n");
      out.write("						<option value=\"4\">Giày</option>\r\n");
      out.write("						<option value=\"5\">Đồng hồ</option>\r\n");
      out.write("					</select>\r\n");
      out.write("\r\n");
      out.write("					<!-- Đơn giá -->\r\n");
      out.write("					<label for=\"editPrice\" class=\"form-label\">Đơn giá</label> <input\r\n");
      out.write("						type=\"number\" class=\"form-control\" id=\"editPrice\" name=\"price\"\r\n");
      out.write("						placeholder=\"Đơn vị: $\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Ảnh -->\r\n");
      out.write("					<label for=\"editImg\" class=\"form-label\">Ảnh:</label><br> <input\r\n");
      out.write("						type=\"file\" id=\"editImg\" name=\"image\" accept=\"image/*\" required>\r\n");
      out.write("\r\n");
      out.write("					<!-- Mô tả sản phẩm -->\r\n");
      out.write("					<label for=\"editDetail\" class=\"form-label\">Mô tả</label>\r\n");
      out.write("					<textarea class=\"form-control\" id=\"editDetail\" name=\"description\"\r\n");
      out.write("						placeholder=\"Mô tả sản phẩm\"></textarea>\r\n");
      out.write("\r\n");
      out.write("					<!-- Nút submit -->\r\n");
      out.write("					<button type=\"submit\" id=\"cuppha\" class=\"btn btn-primary\">Sửa</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"card detailForm hide\" id=\"detailF\">\r\n");
      out.write("			<div class=\"card-body row \">\r\n");
      out.write("				<h5 class=\"card-title\">Chi tiết sản phẩm</h5>\r\n");
      out.write("\r\n");
      out.write("				<!-- Vertical Form -->\r\n");
      out.write("				<form>\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<!-- Sử dụng lớp 'table-responsive' của Bootstrap để tạo thanh cuộn -->\r\n");
      out.write("						<div class=\"table-responsive\" style=\"max-height: 400px;\">\r\n");
      out.write("							<table class=\"table datatable\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>Màu sắc</th>\r\n");
      out.write("										<th>Kích cỡ</th>\r\n");
      out.write("										<th>Số lượng</th>\r\n");
      out.write("										<th>Hành động</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									");

									for (ChiTietSanPham c : chitiet) {
									
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>");
      out.print(c.getMauSac());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(c.getKichCo());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(c.getSoLuong());
      out.write("</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<!-- Các nút sửa và xóa được đặt trong một div với lớp 'btn-group' -->\r\n");
      out.write("											<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\r\n");
      out.write("												<button id=\"editsB\" onclick=\"editsForm()\" type=\"button\"\r\n");
      out.write("													class=\"btn btn-outline-warning\">Sửa</button>\r\n");
      out.write("\r\n");
      out.write("												<!-- Nút xóa -->\r\n");
      out.write("												<form action=\"Xoachitietproductquantri\" method=\"POST\"\r\n");
      out.write("													class=\"d-inline\">\r\n");
      out.write("													<input type=\"hidden\" name=\"id\"\r\n");
      out.write("														value=\"");
      out.print(c.getIdChiTietSanPham());
      out.write("\">\r\n");
      out.write("													<button type=\"submit\" class=\"btn btn-outline-danger\">Xoá</button>\r\n");
      out.write("												</form>\r\n");
      out.write("											</div>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("				<!-- Vertical Form -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"card editForm hide\" style=\"z-index: 2222\" id=\"editS\">\r\n");
      out.write("			<div class=\"card-body row \">\r\n");
      out.write("				<h5 class=\"card-title\">Sửa kiểu</h5>\r\n");
      out.write("\r\n");
      out.write("				<!-- Vertical Form -->\r\n");
      out.write("				<form>\r\n");
      out.write("					<label for=\"editColor\" class=\"form-label\">Màu sắc</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"editColor\"\r\n");
      out.write("						placeholder=\"Màu sắc\"> <label for=\"inputSize\"\r\n");
      out.write("						class=\"form-label\">Kích cỡ</label> <select class=\"form-select\"\r\n");
      out.write("						id=\"editSize\">\r\n");
      out.write("						<option selected>Chọn kích cỡ...</option>\r\n");
      out.write("						<option value=\"S\">S</option>\r\n");
      out.write("						<option value=\"M\">M</option>\r\n");
      out.write("						<option value=\"L\">L</option>\r\n");
      out.write("						<option value=\"XL\">XL</option>\r\n");
      out.write("						<option value=\"XXL\">XXL</option>\r\n");
      out.write("						<option value=\"3XL\">3XL</option>\r\n");
      out.write("					</select> <label for=\"editQuantity\" class=\"form-label\">Số lượng</label> <input\r\n");
      out.write("						type=\"number\" class=\"form-control\" id=\"editQuantity\"\r\n");
      out.write("						placeholder=\"Số lượng\">\r\n");
      out.write("\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-primary\">Sửa</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- End #main -->\r\n");
      out.write("	<div id=\"smoke\" class=\"smoke hide\"></div>\r\n");
      out.write("	<div id=\"smoke2\" class=\"smoke hide\" style=\"z-index: 2221\"></div>\r\n");
      out.write("	<!-- ======= Footer ======= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#\"\r\n");
      out.write("		class=\"back-to-top d-flex align-items-center justify-content-center\"><i\r\n");
      out.write("		class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Vendor JS Files -->\r\n");
      out.write("	<script src=\"assetsquantri/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/chart.js/chart.umd.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/quill/quill.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"assetsquantri/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Main JS File -->\r\n");
      out.write("	<script src=\"assetsquantri/js/main.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	document.getElementById('addb').addEventListener('click', toggleUpload);\r\n");
      out.write("	function toggleUpload() {\r\n");
      out.write("	    const addForm = document.getElementById('addf');\r\n");
      out.write("	    addForm.classList.toggle('hide');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	document.getElementById('adds').addEventListener('click', styleUpload);\r\n");
      out.write("	function styleUpload() {\r\n");
      out.write("	    const addStyle = document.getElementById('addstyle');\r\n");
      out.write("	    addStyle.classList.toggle('hide');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	const form = document.getElementById('inputForm');\r\n");
      out.write("	const submitButton = document.getElementById('submitButton');\r\n");
      out.write("	const tableBody = document.querySelector('#recordsTable tbody');\r\n");
      out.write("\r\n");
      out.write("	let records = [];\r\n");
      out.write("	const updateTable = () => {\r\n");
      out.write("	    tableBody.innerHTML = \"\";\r\n");
      out.write("	    if (records.length === 0) {\r\n");
      out.write("	        tableBody.innerHTML = `<tr><td>Chưa có kiểu dáng nào được thêm</td></tr>`;\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("	    records.forEach((record, index) => {\r\n");
      out.write("	        const row = document.createElement('tr');\r\n");
      out.write("	        row.innerHTML = `\r\n");
      out.write("	            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${record.color}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${record.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${record.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	        `;\r\n");
      out.write("	        tableBody.appendChild(row);\r\n");
      out.write("	    });\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	submitButton.addEventListener('click', () => {\r\n");
      out.write("	    const color = document.getElementById('inputColor').value.trim();\r\n");
      out.write("	    const size = document.getElementById('inputSize').value.trim();\r\n");
      out.write("	    const quantity = document.getElementById('inputQuantity').value.trim();\r\n");
      out.write("\r\n");
      out.write("	    if (!color || !size || !quantity) {\r\n");
      out.write("	        alert(\"hãy nhập đầy đủ các mục\");\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    records.push({ color, size, quantity });\r\n");
      out.write("	    updateTable();\r\n");
      out.write("	    form.reset();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* function editForm() {\r\n");
      out.write("    const editF = document.getElementById('editF');\r\n");
      out.write("    const smoke = document.getElementById('smoke');\r\n");
      out.write("    editF.classList.remove('hide');\r\n");
      out.write("    smoke.classList.remove('hide');\r\n");
      out.write("} */\r\n");
      out.write("//Hàm mở modal\r\n");
      out.write("function editForm(button) {\r\n");
      out.write("    const editF = document.getElementById('editF'); // Modal chỉnh sửa\r\n");
      out.write("    const smoke = document.getElementById('smoke'); // Lớp mờ nền\r\n");
      out.write("    const productIdInput = document.getElementById('product-id'); // Ô input chứa ID sản phẩm\r\n");
      out.write("\r\n");
      out.write("    // Lấy ID từ nút bấm và gán vào ô input\r\n");
      out.write("    const productId = button.getAttribute('data-id');\r\n");
      out.write("    productIdInput.value = productId;\r\n");
      out.write("\r\n");
      out.write("    // Hiển thị modal và lớp mờ nền\r\n");
      out.write("    editF.classList.remove('hide');\r\n");
      out.write("    smoke.classList.remove('hide');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Hàm đóng modal\r\n");
      out.write("function closeModal(event) {\r\n");
      out.write("    const editF = document.getElementById('editF');\r\n");
      out.write("    const smoke = document.getElementById('smoke');\r\n");
      out.write("\r\n");
      out.write("    // Nếu click vào lớp mờ hoặc nút đóng\r\n");
      out.write("    if (!event || event.target === smoke || event.target.classList.contains('close-btn')) {\r\n");
      out.write("        editF.classList.add('hide');\r\n");
      out.write("        smoke.classList.add('hide');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Xử lý nút lưu\r\n");
      out.write(" function handleSave(event) {\r\n");
      out.write("   /*  event.preventDefault(); // Ngăn chặn reload trang\r\n");
      out.write("    alert('Đã lưu thông tin!'); */\r\n");
      out.write("    closeModal(); // Đóng modal sau khi lưu\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("function detailForm() {\r\n");
      out.write("    const detailF = document.getElementById('detailF');\r\n");
      out.write("    const smoke = document.getElementById('smoke');\r\n");
      out.write("    detailF.classList.remove('hide');\r\n");
      out.write("    smoke.classList.remove('hide');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.getElementById('smoke').addEventListener('click', function () {\r\n");
      out.write("    document.getElementById('smoke').classList.add('hide');\r\n");
      out.write("    document.getElementById('editF').classList.add('hide');\r\n");
      out.write("    document.getElementById('detailF').classList.add('hide');\r\n");
      out.write("    saveTabState('');\r\n");
      out.write("});\r\n");
      out.write(" function editsForm() {\r\n");
      out.write("    const editS = document.getElementById('editS');\r\n");
      out.write("    const smoke = document.getElementById('smoke2');\r\n");
      out.write("    editS.classList.remove('hide');\r\n");
      out.write("    smoke2.classList.remove('hide');\r\n");
      out.write("} \r\n");
      out.write("document.getElementById('smoke2').addEventListener('click', function () {\r\n");
      out.write("    document.getElementById('smoke2').classList.add('hide');\r\n");
      out.write("    document.getElementById('editS').classList.add('hide');\r\n");
      out.write("    saveTabState('');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Lưu trạng thái tab vào Local Storage\r\n");
      out.write("function saveTabState(tabId) {\r\n");
      out.write("    localStorage.setItem('activeTab', tabId);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Khôi phục trạng thái tab khi load lại trang\r\n");
      out.write("window.addEventListener('load', () => {\r\n");
      out.write("    const activeTab = localStorage.getItem('activeTab');\r\n");
      out.write("    if (activeTab) {\r\n");
      out.write("        document.getElementById(activeTab)?.classList.remove('hide');\r\n");
      out.write("        document.getElementById('smoke')?.classList.remove('hide');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("//Sử dụng sự kiện click cho tất cả các nút sửa\r\n");
      out.write("document.querySelectorAll('.editB').forEach(button => {\r\n");
      out.write("    button.addEventListener('click', function() {\r\n");
      out.write("        var productId = this.getAttribute('data-id');\r\n");
      out.write("        // Mở form sửa sản phẩm hoặc xử lý các hành động khác\r\n");
      out.write("        console.log(\"Sửa sản phẩm với ID: \" + productId);\r\n");
      out.write("        // Thực hiện các thao tác liên quan, ví dụ hiển thị form sửa\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
